### ISSUE TITLE
Error of the script at the home page

### ISSUE THREAD

**Issue by YuanxiLiu** [louisepb/TexGen#56]
Hallo everyone,
I tried to run the "Example 6: A layered textile" script and it showed Error. Please check if it works for you. Thanks a lot.
https://texgen.sourceforge.net/index.php/Scripting_Create_Models
Best Regards,
Sissy

**Comment by louisepb** [comment]
Hello Sissy,
The requirements for 'bool' in Python have become more stringent since these scripts were written.  If you make the last two arguments in the CTextileWeave2D function call False then the script should work. I will update the version on the webpage.
Thanks,
Louise

**Comment by louisepb** [comment]
Hello @YuanxiLiu ,
The problem is with the last two parameters in the call to CTextileWeave2D. These define whether the refine option is used and whether in-plane tangents are used at the master nodes. They are bool arguments and this has been tightened up in Python so the arguments now need to use the bool operator, bool(0) or bool(1), or True or False.
I will make the change on the website.
Best wishes,
Louise
