### ISSUE TITLE
How can I change Texgen to use python3.10.5? I would appreciate any suggestions.

### ISSUE THREAD

**Issue by bairizhuozhuo** [louisepb/TexGen#60]
How can I change Texgen to use python3.10.5? I would appreciate any suggestions.

**Comment by louisepb** [comment]
Hi, I haven't tried building TexGen with python 10.  If you want to try then you will need to rebuild the code, putting the correct python version etc into cmake.  If it throws up errors due to changes between python 9 and 10 then you may need to work out how to resolve this.  If you do, you're welcome to make a pull request to update the project :-)

**Comment by bairizhuozhuo** [comment]
Thanks for the suggestion, it sounds like it would take a lot of time. I haven't gotten to the point where I need to do that yet, but I'd be very interested in trying it out when I have the time.
